version: '3.10'
volumes:
  database_data:
  app_data:

services:
  db:
    image: postgres:15
    container_name: lighthouse_db
    restart: always
    volumes:
      - database_data:/lighthouse/resources:rw
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lighthouse_db
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: lighthouse_redis
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf

  lighthouse_app:
    build:
      context: .
    container_name: lighthouse_app
    volumes:
      - app_data:/lighthouse/resources:rw
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["./scripts/docker_app.sh"]
    ports:
      - 9000:8000

  celery:
    build: 
      context: .
      dockerfile: Dockerfile-celery
    container_name: lighthouse_celery
    env_file:
      - .env
    restart: always
    depends_on:
      - lighthouse_app
      - redis
    command: ["./scripts/docker_celery.sh", "celery"]

  flower:
    build: 
      context: .
      dockerfile: Dockerfile-celery
    container_name: lighthouse_flower
    env_file:
      - .env
    restart: always
    depends_on:
      - lighthouse_app
      - redis
    ports:
      - 5555:5555
    command: ["./scripts/docker_celery.sh", "flower"]



