import sqlalchemy_utils

"""V.1

Revision ID: 7b514a062d32
Revises: 
Create Date: 2023-04-08 17:02:34.605026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b514a062d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('tag',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('name_tag', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_tag')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=11), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('event',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('name_event', sa.String(length=200), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('time_event', sa.TIMESTAMP(), nullable=True),
    sa.Column('place_event', sa.String(), nullable=True),
    sa.Column('about_event', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id_organizer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ),
    sa.ForeignKeyConstraint(['id_organizer'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('table_event_tag',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['event.id_event'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.id_tag'], ),
    sa.PrimaryKeyConstraint('event', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_event_tag')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
