"""Database create

Revision ID: ab96572f76d1
Revises: 
Create Date: 2023-04-07 14:44:15.569092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab96572f76d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('tags',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('name_tag', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_tag')
    )
    op.create_table('events',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('name_event', sa.String(length=200), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('time_event', sa.TIMESTAMP(), nullable=True),
    sa.Column('place_event', sa.String(), nullable=True),
    sa.Column('about_event', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('table_event_tag',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['events.id_event'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.id_tag'], ),
    sa.PrimaryKeyConstraint('event', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_event_tag')
    op.drop_table('events')
    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
